---
title: "First RMD in Git"
author: "Douglas Tan"
date: "2023/01/16"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
knitr::opts_chunk$set(echo = TRUE)
require('tidyverse')
```

## R Markdown

Here are some of my favorite things:
1. Playing guitar
2. Taking photos
3. Bouldering

When you click the **Knit** button a document will be generated that includes both content as well as the output of any embedded R code chunks within the document. You can embed an R code chunk like this:

```{r mpg}
summary(mpg)
```

## Average MPG

You can also embed plots, for example:

```{r avgmpg}
avgmpgdata <- mpg %>%
 group_by(manufacturer) %>%
 summarize(hwy = mean(hwy), cty = mean(cty))

g <- ggplot(data = avgmpgdata)
g + geom_col(aes(x = cty, y = reorder(manufacturer, cty), fill = manufacturer)) +
 ggtitle("Average Miles per Gallon for City Driving by Manufacturer", subtitle = "Data on vehicles from 1999 to 2008 for 38 popular models of cars") +
 theme(legend.position="none")
  
```
